### ISSUE TITLE
[CI] Adicionar Github actions

### ISSUE THREAD

**Issue by gondekr** [ingresse/ios-sdk#134]
# Descrição
Adicionar workflow básico do github actions com testes

## Requisitos
Máquina: ```macOS-latest```
Versão do Xcode: ```11.2```

## Sintaxe de exemplo
```yml
name: Regular branch
on: [push]
jobs:
  test:
    name: Test Job
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Fastlane test
      run: fastlane test
```
